name: i18n Staging Deploy to GitHub Pages

on:
  push:
    branches:
      - japanese-pages-staging

env:
  HUGO_ENV: "production"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true
      - name: Copy the missing files from /content/en for publishing each language site
        run: |
          for i in de es fr it ja ru zh; do
            rsync -rv --ignore-existing content/en/ content/$i/ --log-file=content/.gitignore;
            sed -i "s/^.\{37\} /$i\//g" content/.gitignore;
            sed -i '/total size\|file list/d' content/.gitignore;
          done
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public/
          publish_branch: gh-pages-staging
