name: Links Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 18 * * 5'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          fail: true
          jobSummary: true
          args: --verbose --no-progress --exclude-mail --exclude-path content/events/ content/learn/learning-path/ -- content
